[package]
name = "runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db-manager = { path = "../db-manager" }

anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
crossterm = "0.27.0"
ratatui = { version = "0.23.0", features = ["all-widgets"] }
rand = "0.8.5"
